name: Build ana Unit Test Cookbook App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SofUni Username
      run: echo 'teodor555'
      
  ui_tests:
    needs: build_and_unit_test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Start Cookbook App
      run: npm start &
    - name: Run UI Tests
      run: npm run test:ui
  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: ui_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
