name: Build ana Unit Test Cookbook App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SofUni Username
      run: echo 'teodor555'
